import random


class Questions:
    import random
    question_lib = [
        {"question": "A slug's blood is green.", "answer": "True"},
        {"question": "The loudest animal is the African Elephant.", "answer": "False"},
        {"question": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
        {"question": "The total surface area of human lungs is about the size of a football pitch.", "answer": "True"},
        {"question": "Lightning never strikes the same place twice.", "answer": "False"},
        {"question": "Honey never spoils.", "answer": "True"},
        {"question": "Goldfish have a memory of only three seconds.", "answer": "False"},
        {"question": "The Great Wall of China is visible from space with the naked eye.", "answer": "False"},
        {"question": "Bananas grow on trees.", "answer": "False"},
        {"question": "An octopus has three hearts.", "answer": "True"},
        {"question": "Humans can distinguish over a trillion different smells.", "answer": "True"},
        {"question": "Adult humans have 206 bones.", "answer": "True"},
        {"question": "The human body has four lungs.", "answer": "False"},
        {"question": "Penguins can fly.", "answer": "False"},
        {"question": "The capital of Australia is Sydney.", "answer": "False"},
        {"question": "There are more stars in the universe than grains of sand on Earth.", "answer": "True"},
        {"question": "Sharks are mammals.", "answer": "False"},
        {"question": "A tomato is a fruit.", "answer": "True"},
        {"question": "Antarctica is the largest desert on Earth.", "answer": "True"},
        {"question": "Humans and chimpanzees share about 98 percent of their DNA.", "answer": "True"},
        {"question": "The speed of light is about 300,000 kilometers per second.", "answer": "True"},
        {"question": "Water boils at 100°C at sea level.", "answer": "True"},
        {"question": "The human heart is located on the right side of the chest.", "answer": "False"},
        {"question": "Mercury is the hottest planet in the solar system.", "answer": "False"},
        {"question": "Bats are blind.", "answer": "False"},
        {"question": "Sound travels faster in water than in air.", "answer": "True"},
        {"question": "A group of crows is called a murder.", "answer": "True"},
        {"question": "Mount Everest is the tallest mountain above sea level.", "answer": "True"},
        {"question": "The Amazon is the largest rainforest in the world.", "answer": "True"},
        {"question": "Humans have more than five senses.", "answer": "True"},
        {"question": "The human body has no living bacteria inside it.", "answer": "False"},
        {"question": "Venus spins in the opposite direction to most planets.", "answer": "True"},
        {"question": "A day on Venus is longer than a year on Venus.", "answer": "True"},
        {"question": "Dolphins are fish.", "answer": "False"},
        {"question": "The square root of 2 is a rational number.", "answer": "False"},
        {"question": "Zero is an even number.", "answer": "True"},
        {"question": "The boiling point of water increases with altitude.", "answer": "False"},
        {"question": "Lightning is hotter than the surface of the Sun.", "answer": "True"},
        {"question": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
        {"question": "Humans can breathe and swallow at the same time.", "answer": "False"},
        {"question": "Diamonds are made of carbon.", "answer": "True"},
        {"question": "The human liver can regenerate partially after damage.", "answer": "True"},
        {"question": "Tomatoes were once thought to be poisonous in Europe.", "answer": "True"},
        {"question": "Koalas are bears.", "answer": "False"},
        {"question": "The Moon has its own light source.", "answer": "False"},
        {"question": "A leap year occurs every 4 years without exception.", "answer": "False"},
        {"question": "The blue whale is the largest animal ever known.", "answer": "True"},
        {"question": "Spider silk is stronger than steel by weight.", "answer": "True"},
        {"question": "Drinking alcohol warms you up on a cold day.", "answer": "False"},
        {"question": "The North Star is the brightest star in the night sky.", "answer": "False"},
    ######################## Easier questions
        {"question": "A slug's blood is green.", "answer": "True"},
        {"question": "The loudest animal is an elephant.", "answer": "False"},
        {"question": "About one quarter of your bones are in your feet.", "answer": "True"},
        {"question": "Your lungs are big enough to cover a football field if stretched out.", "answer": "True"},
        {"question": "Lightning never hits the same place twice.", "answer": "False"},
        {"question": "Honey never goes bad.", "answer": "True"},
        {"question": "Goldfish only remember things for three seconds.", "answer": "False"},
        {"question": "You can see the Great Wall of China from space with your eyes.", "answer": "False"},
        {"question": "Bananas grow on trees.", "answer": "False"},
        {"question": "An octopus has three hearts.", "answer": "True"},
        {"question": "People can smell more than a trillion different smells.", "answer": "True"},
        {"question": "Adults have 206 bones in their body.", "answer": "True"},
        {"question": "People have four lungs.", "answer": "False"},
        {"question": "Penguins can fly.", "answer": "False"},
        {"question": "Sydney is the capital of Australia.", "answer": "False"},
        {"question": "There are more stars in space than grains of sand on Earth.", "answer": "True"},
        {"question": "Sharks are mammals.", "answer": "False"},
        {"question": "A tomato is a fruit.", "answer": "True"},
        {"question": "Antarctica is the biggest desert in the world.", "answer": "True"},
        {"question": "Humans and chimpanzees are very closely related.", "answer": "True"},
        {"question": "Light is super fast.", "answer": "True"},
        {"question": "Water boils at 100 degrees Celsius.", "answer": "True"},
        {"question": "Your heart is on the right side of your chest.", "answer": "False"},
        {"question": "Mercury is the hottest planet.", "answer": "False"},
        {"question": "Bats are blind.", "answer": "False"},
        {"question": "Sound moves faster in water than in air.", "answer": "True"},
        {"question": "A group of crows is called a murder.", "answer": "True"},
        {"question": "Mount Everest is the tallest mountain.", "answer": "True"},
        {"question": "The Amazon is the biggest rainforest.", "answer": "True"},
        {"question": "Humans have more than five senses.", "answer": "True"},
        {"question": "There are no bacteria living inside people.", "answer": "False"},
        {"question": "Venus spins the opposite way from most planets.", "answer": "True"},
        {"question": "One day on Venus is longer than one year there.", "answer": "True"},
        {"question": "Dolphins are fish.", "answer": "False"},
        {"question": "The square root of 2 is a simple fraction.", "answer": "False"},
        {"question": "Zero is an even number.", "answer": "True"},
        {"question": "Water boils faster on mountains than at the beach.", "answer": "False"},
        {"question": "Lightning is hotter than the Sun's surface.", "answer": "True"},
        {"question": "The Pacific Ocean is the biggest ocean.", "answer": "True"},
        {"question": "People can breathe and swallow at the same time.", "answer": "False"},
        {"question": "Diamonds are made of carbon.", "answer": "True"},
        {"question": "The liver can grow back after part is removed.", "answer": "True"},
        {"question": "Long ago, people thought tomatoes were poisonous.", "answer": "True"},
        {"question": "Koalas are bears.", "answer": "False"},
        {"question": "The Moon makes its own light.", "answer": "False"},
        {"question": "Leap years happen every 4 years without exceptions.", "answer": "False"},
        {"question": "The blue whale is the biggest animal ever.", "answer": "True"},
        {"question": "Spider silk is stronger than steel of the same size.", "answer": "True"},
        {"question": "Drinking alcohol makes you warmer.", "answer": "False"},
        {"question": "The North Star is the brightest star in the sky.", "answer": "False"},
    ]
    used_questions = []
    def get_question(self):
        i = random.randint(0,len(self.question_lib)-1)
        while i  in self.used_questions:
            i = random.randint(0, len(self.question_lib) - 1)
        self.used_questions.append(i)
        result = [i, self.question_lib[i]]
        return result
